---
title: "Зачёт по стохастическому анализу. 2017"
date: "1 июня 2017"
output: pdf_document
lang: ru-RU
header-includes:
   - \usepackage{booktabs}
---


#### Задача 1

Совместный закон распределения пары случайных величин представлен табличкой

\begin{tabular}{*{5}{c}}
\toprule
 & $X=0$, $Y=0$ & $X=0$, $Y=1$ & $X=1$, $Y=0$ & $X=1$, $Y=1$\\
\midrule
Вероятность & $0.1$ & $0.2$ & $0.3$ & $0.4$ \\
\bottomrule
\end{tabular}

1. Найдите $E(Y|X)$ и представьте ответ в виде функции от $X$

2. Найдите $Var(Y|X)$ и представьте ответ в виде функции от $X$

#### Задача 2

Рассмотрим процесс $Y_t = \exp(at - 2W_t)$.

1. Найдите $dY_t$ в краткой и полной форме записи.

2. При каком $a$ процесс $Y_t$ будет мартингалом?

#### Задача 3

Величины $Z_1$, $Z_2$, $Z_3$, \ldots независимы и одинаково распределены. Каждая из них принимает значение $0.5$ c вероятностью $p$ и значение $4$ с вероятностью $1-p$. 

Рассмотрим процесс $X_n = Z_1 \cdot Z_2 \cdot \ldots \cdot Z_n$.

1. Является ли процесс $Z_n$ мартингалом при $p=0.5$?

2. Является ли процесс $X_n$ мартингалом при $p=0.5$?

3. При каком $p$ процесс $Z_n$ будет мартингалом?

4. При каком $p$ процесс $X_n$ будет мартингалом?

#### Задача 4

В рамках модели Блэка-Шоулса цена акции подчиняется уравнению $dS_t = \mu S_t \, dt + \sigma S_t \, dW_t$. 

1. Найдите $dY_t$, если $Y_t = S_t^2$.

2. Запишите формулу для $dY_t$ в полной записи

3. Является ли $Y_t$ мартингалом?

#### Задача 5

В рамках модели Блэка-Шоулса найдите цену в момент времени $0$ бумаги, которая в момент времени $t=2$ приносит прибыль (или убыток) в размере $X_2 = \ln S_1$. Здесь $S_u$ — цена акции в момент времени $u$. Параметры модели Блэка-Шоулса равны $\mu = 0.3$, $r=0.05$, $\sigma = 0.1$, $S_0 = 100$.








