# Сигма-алгебра ($\sigma(x)$ - алгебра) {#sigma_algebra}

Дата: 25 сентября 2016

Конспект: Вероника Закирова

## Повторение.

Прежде чем перейти к рассмотрению задач, давайте вспомним сами определения сигма-алгебры.

#### Определение (интуитивное):
Пусть $Х$ - температура завтра. Я знаю $Х$, а значит, что я могу различать (гарантированно сказать, произошло ли событие вне зависимоти от исхода эксперимента) события сигма-алгебры $\mathcal{F}$:


* $\{ X>10 \in  \mathcal{F}\}$

* $\{X=10 \in  \mathcal{F}\}$

#### Определение (формальное): 
$\sigma(x)$ - минимальная $\sigma$ алгебра, порожденная величиной $X$, то есть - это список событий, которые различает индивид, знающий $X$.

 $\sigma(x)$ - самая маленькая $\sigma$ алгебра, содержащая все события вида: 
$\{X \leqslant A\}$, например, $\{X \leqslant 7\}$ и так далее.

В сигма-алгебру входит еще объединение, пересечение, дополнение событий:

$\{X \leqslant 7\} \in  \mathcal{F} \Rightarrow \{X \geqslant 7\} \in  \mathcal{F}$

## Упражненение.


Пусть монетку подбросили один раз. $Z$ - некий показатель, который в зависомости от произошедшего события принимает определеное значение. 

$\Omega$|орёл|решка|ребро 
-|-|-|-
p|0.49|0.49|0.02
Z|5|7|5

Определить: 

а) минимальную $\sigma$-алгебру на пространстве элементарных исходов $\Omega$

б) $\mathcal{F}$ - самую большую $\sigma$-алгебру на пространстве элементарных исходов $\Omega$

а) рассмотрим различные значения, которые может принимать $Z$:

* $Z \leqslant 0 - \varnothing$
* $Z \leqslant 5 - \{орел, ребро\}$
* $Z = 7 -  \{решка\}$
* $Z \leqslant 20 -  \Omega$

Получаем:
$\sigma(Z) =\{ \varnothing,\{орел,ребро\}, \{решка\}, \Omega \}.$

б) Для того, чтобы получить $\mathcal{F}$ необходимо применить элементарные операции над множествами к элементам $\sigma(x)$: 
$\mathcal{F} =\{ \varnothing,\{орел\}, \{ребро\},\{решка\}, не\ решка, не\ орел, не\ ребро,  \Omega \}.$


## Упражнение с пары №2 (семинар 1). [Доразбор]


В ходе эксперимента монетку подбрасывают бесконечное число раз. есть два наблюдателя: Петры и Николаи.

Пётр$_i$ видит все события, начиная с $i$ - его сигма-алгебра $\mathcal{F}_i$.

Николай$_i$ видит все события, которые произошли до $i$ -- его сигма-алгебра $\mathcal{H}_i$.

Напомним: $A_i =\{на\ i-й\ раз\ выпал\ орел\}$

В какие $\sigma$-алгебры входят следующие события:

* $\underset{i=1}{\overset{\infty}\cap}(\underset{j=1}{\overset{\infty}\cup}A_j)$ ;
* $\underset{i=1}{\overset{\infty}\cup}(\underset{j=1}{\overset{\infty}\cap}A_j)$ ?

Решение:

1. $\underset{i=1}{\overset{\infty}\cap}(\underset{j=1}{\overset{\infty}\cup}A_j)$ 

Распишем это событие подробнее и назовем его $B$:

$(\underset{j=1}{\overset{\infty}\cup}A_j)\cap (\underset{j=2}{\overset{\infty}\cup}A_j) \cap (\underset{j=3}{\overset{\infty}\cup}A_j)\dots  = B$ 

$\underbrace{(\underset{j=1}{\overset{\infty}\cup}A_j)}_{хоть\ 1\ орел\ с\ 1го\ броска}\underbrace{\cap}_{и}\underbrace{ (\underset{j=2}{\overset{\infty}\cup}A_j)}_{хоть\ 1\ орел\ со\ 2го\ броска} \underbrace{\cap}_{и}\underbrace{ (\underset{j=3}{\overset{\infty}\cup}A_j)}_{хоть\ 1\ орел\ с\ 3го\ броска}\underbrace{\dots}_{и\ тд.}$

Событие $B$ можно записать словами так: орел выпал $\infty$ число раз.

Примеры: 

* $PPPPPPP \dots$ - $B$ не случилось
* $POOOOPPPPP \dots$ - $B$ не\ случилось
* $POPOPOPOPO \dots$ - $B$ случилось
* $POPOOPOOOPOOOOPOOOOO \dots$ - $B$ случилось

Событие $B$ входит в сигма-алгебры: 

$B \in \mathcal{F}_1, B \in \mathcal{F}_2, \dots$ , то есть все Петры смогут сказать произошло ли оно.

Так как каждый их Николаев видит лишь конечное число событий, то 
$B \not\in \mathcal{H}_i$

2. $\underset{i=1}{\overset{\infty}\cup}(\underset{j=1}{\overset{\infty}\cap}A_j)$

По аналогии с $B$ распишем это событие подробнее и назовем его $С$:

$(\underset{j=1}{\overset{\infty}\cap}A_j)\cup (\underset{j=2}{\overset{\infty}\cap}A_j) \cup (\underset{j=3}{\overset{\infty}\cap}A_j)\dots  = С$ 

$\underbrace{(\underset{j=1}{\overset{\infty}\cap}A_j)}_{все\ орлы\ с\ 1го\ броска}\underbrace{\cup}_{или}\underbrace{ (\underset{j=2}{\overset{\infty}\cap}A_j)}_{все\ орлы\ со\ 2го\ броска}\underbrace{\cap}_{или}\underbrace{ (\underset{j=3}{\overset{\infty}\cap}A_j)}_{все\ орлы\ с\ 3го\ броска}\underbrace{\dots}_{и\ тд.}$


Резюмируя, событие $C$ можно записать словами так: решек выпало конечное число.

Примеры: 

* $PPPPPPP \dots$ - $С$ не случилось
* $POOOOPPPPP \dots$ - $С$ не случилось
* $PPPOOOOOOOO \dots$ - $С$ случилось
* $OPPOOPOOOOO \dots$ - $С$ случилось

Событие $C$ входит в сигма-алгебры: 

$C \in \mathcal{F}_1, C \in \mathcal{F}_2, \dots$ , то есть все Петры смогут сказать произошло ли оно.

Так как каждый их Николаев видит лишь конечное число событий, то 
$C \not\in \mathcal{H}_i$



#### Приложение.

При наборе данного семинара, приходилось практически постоянно переключать раскладки с EN на RUS и наоборот, да и почти каждому знакома проблема "напечатал много предложений, поднял голову, а там на английской раскладке все".

Если Вы все еще перепечатываете текст, тогда [punto switcher](https://yandex.ru/soft/punto/) специально для Вас.


