# Грибная задача {#example_for cardinality_and_measurability} ???????????


## Продолжение грибной задачки (№ 2.32 в задачнике) с предыдущей лекции. ????????????/


Конспект: Голованова Лиза

дата: 16 сентября 2016


### Условия задачи:

В лесу есть три вида грибов: рыжики, лисички и мухоморы. Попадаются они равновероятно и независимо друг от друга. Маша нашла 100 грибов. Пусть R — количество рыжиков, L — количество лисичек, а M — количество мухоморов среди этих трёх видов грибов.


 а) Сколько элементов $\sigma (R)$? 
 
 
 б) Сколько элементов $\sigma (R,M)$?
 
 
 в) Измерима ли $L$ относительно $\sigma (R)$?
 
 
 г) Измерима ли $L$ относительно $\sigma (R,M)$? 
 
 
 д) Измерима ли $L$ относительно $\sigma (R + M)$? 
 
 
 е) Измерима ли $L$ относительно $\sigma (R−M)$? 
 

### Решение б) — е): 

б) Для того, чтобы понять, сколько элементов в $\sigma (R,M)$, сначала определим число элементарных событий в этом множестве.
 

Рассмотрим событие $\{R>M\}\in\mathcal{F}$.
Если приравнять к нему какое-либо число, например, $\{R>M\}=8$, то можно сказать, что $R$ больше $M$ на $8$, то есть измерить $R$ относительно $M$. По такой же логике событие $\{L=5\}=\{R+M=95\}\in\mathcal{F}$. Также $\{R>100-R-L\}\in\mathcal{F}$. Все события такого вида лежат в $\mathcal{F}$. На всякий случай, события, не относящиеся к списку событий, к примеру $\{ \text{Маша пошла в кино } \} \notin\mathcal{F}$. 


События $\{R>M\}\in\mathcal{F}$ можно разбить на элементарные множества, как $\{M=15\}$, $\{R=5\}$. Давайте узнаем, сколько будет таких элементарных событий.


Рассмотрим комбинации возможных элементарных событий при фиксированном $R$:  $\{R=0,M=0\}$,$\{R=0,M=1\}$... Сумма таких событий для $R=0$ составит $101$ событие. Для $R=1$ станет на одно событие меньше, и так далее. $R=100$ достанется один элемент. По формуле арифметической прогрессии подсчитаем сумму таких событий:   $\dfrac{(1+101)\cdot101}{2}$.

Тогда сумма всех элементарных событий будет равно $101\cdot51$. Всего событий будет: $card\sigma(R,M)=2^{101\cdot51}.$


### Для ответа на пункты в) — е) интуитивно и формально определим измеримость:

$\textbf{Интуитивно}$: Если $R$ является $\mathcal{F}$ измеримой, то зная  $\mathcal{F}$ можно сказать, чему равно $R$. Или, по-другому, это список событий, который знает индивид, зная $R$. 


$\textbf{Формально}$: Событие измеримо относительно $\mathcal{F}$, если оно:


1) Обладает свойствами, определяющими $\sigma$-алгебру: 

SA1. $\Omega\in\mathcal{F}$  —  даже ничего не зная, можно быть уверенным, что $\Omega$ — произошло.


SA2. Если $R\notin\mathcal{F}$, то $R^c\in\mathcal{F}$ — даже ничего не зная, можно быть уверенным, что $\varnothing$ не произошло. 

SA3. Если $R_1\in\mathcal{F}$, $R_2\in\mathcal{F}$, $R_3\in\mathcal{F}$ и т.д., то $\bigcup_{i=1}^{\infty} R_i\in\mathcal{F}$.

2) Содержит события вида $\{R \leq n\}\in \sigma (R)$, где $n$ — любое число.

в) Если индивид обладает информацией только о числе рыжиков в корзинке, он не сможет сказать, чему равно число лисичек, ему не хватает знаний о количестве мухоморов. Значит, $L$ не измерима относительно $\sigma (R)$.


г) $L$ измерима относительно $\sigma (R,M)$, потому что мы знаем информацию и о рыжиках, и о мухоморах.


д) Поскольку мы знаем общее число грибов и сумму рыжиков с мухоморами, можно запросто посчитать, чему равно $L$. Значит, $L$ измерима относительно $\sigma (R + M)$.


е) Разница между количеством рыжиков и мухоморов не сможет сообщить, чему будет равно $L$. $L$ не измерима относительно $\sigma (R−M)$.

