# Условное математическое ожидание {#expected_value_definition}

Конспект: Гончар Павел

Дата: 2016-09-30

#### Основные задачи лекции:

+ Сформулировать интуитивное определение условного математического ожидания, используя терминологию $\sigma$ - алгебры.
+ На примере посчитать условное математическое ожидание.
+ Сформулировать формальное определение.

## Формальное определение условного математического ожидания.
 
Будем использовать стандартное обозначение условного математического ожидания: 
$E(X| \mathcal{F})$, где:

$X$ - случайная величина, $\mathcal{F}$ - $\sigma$ - алгебра. Для полноты понимания этого математического обьекта сформулируем интуитивные опредления:

+ $E(X| \mathcal{F})$ - наилучший прогноз $Х$, если различаем события из $\mathcal{F}$.
+ Огрубление случайной величины $Х$ до $\mathcal{F}$ измеримости.
+ Из величин известных индивиду, различающему события из $\mathcal{F}$ выбирается ближайшая к $Х$.

Стоить отметить, что $E(X| \mathcal{F})$ - случайная величина.

## Пример:

Пусть дана случайная величина $X$, принимающая значения 1, 10, 20 с вероятностями 0.5, 0.2, 0,3 соответственно. Пространтсво элементарных исходов $\Omega = \{a, b, c \}$. Заданы две $\sigma$ - алгебры :

1. $\mathcal{F} = \{\varnothing, \Omega, \{a\}, \{a, b\}\}$

2. $\mathcal{A} = \{\varnothing, \Omega\}$

3. $\mathcal{H}$ - все подмножества $\Omega$

Для простоты восприятия составим матрицу:

$P$ | 0.5 | 0.2 | 0.3 |
--- | --- | --- | --- |
$\Omega$ | $a$| $b$ | $c$ |
$X$ | 1 | 10 | 20|

**Найти:** $E(X| \mathcal{F})$, $E(X| \mathcal{H})$, $E(X| \mathcal{A})$.

Найдем сначала $E(X| \mathcal{H})$. Сформулируем наилучший прогноз $X$, при информации $\mathcal{H}$ (используем первое интуитивное определение). Так как мы знаем всю информацию о событиях, то сможем идеально предсказать значения случайной величины, то есть:

$E(X| \mathcal{H}) = X$.

Найдем $E(X| \mathcal{A})$. Так как $\sigma$ - алгебра $\mathcal{A}$ не содержит информации для индификации событий, то рассчитываем ожидаемое значение случайной величины, используя обычную формулу математического ожидания:

$E(X| \mathcal{A})=E(X) = 1 * 0.5 + 10 * 0.2 + 20 * 0.3 = 8.5$

Для нахождения $E(X| \mathcal{F})$ необходимо изучить как устроена $\mathcal{F}$.
Из условия видно, что индивид, обладающий информацией $\mathcal{F}$, не может различить событие $c$ и  $b$, поэтому лучшим ответом на событие $c$ или $b$ будет одно число. Обозначим его - $m$. Заметим, что событие $a$ индивид может индифицировать, поэтому лучшим ответом на событие $a$ будет - 1. Для общего вида обозначим это число, как - $k$. Так как $E(X| \mathcal{F})$ - случайная величина, то добавим ее в матрицу для наглядности решения:
 
$P$ | 0.5 | 0.2 | 0.3 |
--- | --- | --- | --- |
$\Omega$ | $a$| $b$ | $c$ |
$X$ | 1 | 10 | 20|
$E(X\mid\mathcal{F})$ | $k$ | $m$ | $m$ |

Задача сводится к отысканию $k$ и  $m$. Формально задача имеет вид:
$\underset{\hat{x}}{ \min} \ E[(X-\hat{x})^2]$, где:

$X$ - фактические значения

$\hat{x}$ - прогнозное значение.

Для нашей задачи целевая функция $Q(k,m)$ имеет вид:

$Q(k,m) = 0.5 \cdot (1 - k)^2 + 0.2 \cdot (10 - m)^2 + 0.3 \cdot (20 - m)^2$ ,  а задача:


 $\underset{k,m}{ \min}  Q(k,m) $

Решение задачи минимизации: 

$k$ = 1

$m$ = 16

Следовательно получаем следующие наилучшие прогнозы:

$P$ | 0.5 | 0.2 | 0.3 |
---|----|--------|-----|
$\Omega$ | $a$| $b$ | $c$ |
$X$ | 1 | 10 | 20|
$E(X| \mathcal{F})$ | 1 | 16 | 16 |

Полная матрица ответов:

$P$ | 0.5 | 0.2 | 0.3 |
--- | --- | --- | --- |
$\Omega$ | $a$| $b$ | $c$ |
$X$ | 1 | 10 | 20|
$E(X| \mathcal{H})$ | 1 | 10 | 20 |
$E(X| \mathcal{A})$ | 8.5 | 8.5 | 8.5 |
$E(X| \mathcal{F})$ | 1 | 16 | 16 |

## Формальное определение математического ожидания.
Если $E(X| \mathcal{F}) < \infty$, то можно определить $E(X| \mathcal{F})$:

$E(X| \mathcal{F})$ - случайная величина, $\hat{x}$ обладающая следующими свойствами:

1. $\hat{x}$ - измерима относительно $\sigma$ - алгебры $\mathcal{F}$.

2. $E(\hat{x}) = E(x)$.

3. Если взять произвольную  $\mathcal{F}$-измеримую случайную величину $z$, то  $Сov(z,x) = Сov(z, \hat{x})$.
 
