# Мартингалы {#martingales_define}

Конспект: Маслова Инна

дата: 21 октября 2016

## Определение мартингала

### Необходимые сведения перед основным определением
* Определение 1: Случайный процесс в дискретном времени — это последовательность случайных величин $x_1,x_2,x_3,\ldots$
Формальная запись: ($X_n$).
* Определение 2: Фильтрация (поток $\sigma$-алгебр) — последовательность $\sigma$-алгебр $\mathcal{F_1}, \mathcal{F_2}, \mathcal{F_3}, \ldots$ такая, что для любого $n$ $\mathcal{F}_n\subseteq \mathcal{F_{n+1}}$ (последующая $\sigma$-алгебра содержит предыдущую).
* Определение 3: фильтрация $\mathcal{F}_n$ называется естественной фильтрацией для процесса ($X_n$), если все, что я знаю — значение $X$, то есть для любого $n$: $\mathcal{F}_n=\sigma(X_1,X_2,\ldots,X_n)$ ( то есть в 1 день я знаю, что было в $X_1$,во 2 день — что было в $X_1$ и $X_2$ и так далее).

### Определение мартингала
Процесс ($x_n$) называется мартингалом по отношению к фильтрации $\mathcal{F}_n$, если выполнены 2 условия:

1) для любого $n$  $X_n$ измерима относительно $\mathcal{F}_n$ (мне хватает $\mathcal{F}_n$ чтобы сказать, чему равно $X_n$) $\newcommand{E}{\mathsf{E}};$

2) $E (X_{n+1}|\mathcal{F}_n)=X_n.$

Мартингал — процесс, который в среднем не меняется.

## Задачи

### Постановка задачи:

Является ли процесс ($X_n$) мартингалом по отношению к фильтрации $\mathcal{F}_n$?

a) $z_1,z_2,\ldots,z_n$ — независимы и $z_i\sim N(0,49)$, $X_n=\sum_{i=1}^n z_i$. Фильтрация: $\mathcal{F}_n=\sigma(z_1,z_2,\ldots,z_n);$

b) $z_1,z_2,\ldots,z_n$ — независимы и $z_i\sim U[0,1]$, $X_n=\sum_{i=1}^n z_i$. Фильтрация: $\mathcal{F}_n=\sigma(z_1,z_2,\ldots,z_n);$

c) Есть колода карт. Всего 52 карты, 4 масти. Я открываю одну карту за другой и смотрю, какую карту я открыла. Пусть $X_n$ — доля тузов в оставшейся колоде после открытия $n$ карт. $\mathcal{F}_n$ — знаю те карты, которые открыты. Рассмотрим, какие значения могут принимать $X_0$ и $X_{51}.$

$X_0=\dfrac4{52}.$ 

После открытия 51-ой карты, получим, что значения, которые принимает $X_{51}$ будет либо 1 (последняя карта — туз), либо 0 (последняя карта — не туз). Тогда вероятность того, что последняя карта окажется тузом, равна $\dfrac4{52}$, так как всего 4 туза, а количество карт равно 52.

|   Исход  |     Не туз     |     Туз     |
|----------|----------------|-------------|
| $X_{51}$ |       $0$      |     $1$     |
|   $p$    |$\dfrac{48}{52}$|$\dfrac4{52}$|

d) Сколько элементов в $\mathcal{F_1}$ и $\mathcal{F_2}$? Понять, что больше: число элементарных частиц во Вселенной или число элементов в $\mathcal{F_2}$?

### Решение:
Для всех случаев нужно проверить выполнение двух условий из определения мартингала.

**a) Рассмотрим 1-ый случай:**

   1-ое условие: Я знаю $z_1,z_2,\ldots,z_n$ и так как $X_n=\sum_{i=1}^n z_i$, то я знаю $X_n$.

   2-ое условие: $E(X_{n+1}|\mathcal{F}_n) = E(z_1+z_2+\ldots+z_{n+1}|z_1,z_2,\ldots,z_n) =$ (знаю $z_1,z_2,\ldots,z_n$, поэтому могу их вынести) $= z_1+z_2+\ldots+z_n + E(z_{n+1}|z_1,z_2,\ldots,z_n) = z_1+z_2+\ldots+z_n+E (z_{n+1})=z_1+z_2+\ldots+z_n=X_n.$
 
Пояснения ко 2-ому условию: ($E (z_{n+1}) = 0$ так как $z_i \sim N(0,1).$
 
 $E (z_{n+1}|z_1,z_2,\ldots,z_n)=E (z_{n+1})$, так как случайные величины $z_1,z_2,\ldots,z_{n+1}$ — независимы).
 
 Оба условия выполняются, а значит, процесс ($X_n$) — мартингал по отношению к фильтрации $\mathcal{F}_n.$

**b) Рассмотрим 2-ой случай:**

   1-ое условие: Я знаю $z_1,z_2,\ldots,z_n$ и так как $X_n=\sum_{i=1}^n z_i$, то я знаю $X_n.$

   2-ое условие: $E (X_{n+1}|\mathcal{F}_n)=E (z_1+z_2+\ldots+z_{n+1}|z_1,z_2,\ldots,z_n) =$ (знаю $z_1,z_2,\ldots,z_n$, поэтому могу их вынести) $= z_1+z_2+\ldots+z_n+E (z_{n+1}|z_1,z_2,\ldots,z_n) = z_1+z_2+\ldots+z_n+E (z_{n+1}) = z_1+z_2+\ldots+z_n+\dfrac{0+1}{2}=X_n+\dfrac12 \ne X_n.$ 

2-ое условие не выполняется, а значит, в этом случае процесс ($X_n$) — не является мартингалом.

**c) Рассмотрим 3-ий случай:**

   1-ое условие: выполнено, так как если я вижу открытые карты, то могу посчитать долю тузов среди неоткрытых, то есть могу посчитать $X_n.$
   
   2-ое условие:
 Спрогнозируем долю тузов, когда открою следующую карту : $E (X_{n+1}|\mathcal{F}_n).$
 
 Сейчас: открыто $n$, закрыто $52-n.$
         
 Доля тузов среди закрытых карт: $X_n.$
 
 Количество закрытых тузов: $X_n(52-n).$
 
 Тогда вероятность того, что при открытии $n+1$ карты будет туз, равна доле тузов среди закрытых карт или $X_n$. Если карта — туз, то после её открытия доля тузов будет равна $X_{n+1}=\dfrac{(52-n)X_n-1}{51-n}$. Если же при открытии карта окажется не тузом, то $X_{n+1}=\dfrac{(52-n)X_n}{51-n}$. Ниже представлена таблица с долями тузов и вероятностями исходов.
 
|  Исход  |           Туз             |         Не туз          |
|---------|---------------------------|-------------------------|
|$X_{n+1}$|$\dfrac{(52-n)X_n-1}{51-n}$|$\dfrac{(52-n)X_n}{51-n}$|
|   $p$   |            $X_n$          |          $1-X_n$        |
 
  
  

$E (X_{n+1}|\mathcal{F}_n) = X_n\dfrac{(52-n)X_n-1}{51-n}+(1-X_n)\dfrac{(52-n)X_n}{51-n} = \dfrac{52X_n^2-nX_n^2-X_n+52X_n-52X_n^2-nX_n+nX_n^2}{51-n}=\dfrac{51X_n-nX_n}{51-n}=X_n$ 

2-ое условие выполняется.

Оба условия выполняются, а значит, процесс ($X_n$) — мартингал по отношению к фильтрации $\mathcal{F}_n.$

**d) Последнее задание**

$\mathcal{F_1}$ содержит 52 элементарных события (например, карта №1 — дама $\clubsuit$, карта №2 — туз $\spadesuit$ и т.д.). Каждое событие либо включаем либо не включаем, поэтому получим $card\mathcal{F_1}=2^{52}.$

$card\mathcal{F_2}=2^{C_{52}^1C_{51}^1}=2^{52\cdot51} \approx (4 \cdot 10^{15})^{51}=4^{51} \cdot 10^{15\cdot51}$ 

Число элементарных частиц во Вселенной $\approx 10^{81}$

$4^{51}\cdot 10^{15\cdot51} \gg 10^{81}$

## Зачем изучать мартингалы?
В реальности случайные процессы — не мартингалы. Можно сделать из процесса мартингал, изучить его (всё просто считается), сделать какие-то выводы, а затем, используя эти выводы, изучить исходный процесс.

**Упражнение**

$z_1,z_2,\ldots,z_n$ — независимы и $z_i\sim U[0,1]$, $X_n=\sum_{i=1}^n z_i.$ Фильтрация: $\mathcal{F}_n=\sigma(X_1,X_2,\ldots,X_n).$ Возьмём процесс $M_n=a^{X_n}$. Нужно подобрать число $a$ так, чтобы $(M_n)$ был мартингалом относительно фильтрации $\mathcal{F}_n$.

**Решение**

Простой случай: $a = 1$. Действительно, $(M_n) = (1,1,1,1,\ldots)$. Тогда $E (M_{n+1}|\mathcal{F}_n)=1=M_n$, а значит, $(M_n)$ — мартингал. 

Теперь попробуем найти $a \ne 1$. Для этого проверим выполнимость двух условий из определения мартингала.

1-ое условие: $M_n$ измерим относительно $\mathcal{F}_n$ при известном $a.$

2-ое условие: $E (M_{n+1}|\mathcal{F}_n)=E (a^{X_{n+1}}|\mathcal{F}_n)=E (a^{z_1+z_2+\ldots+z_{n+1}}|\mathcal{F}_n) =$ (знаю $z_1,z_2,\ldots,z_n$, поэтому могу их вынести) $= a^{z_1+z_2+\ldots+z_n}E (a^{z_{n+1}}|\mathcal{F}_n)=a^{X_n}E (a^{z_{n+1}}|\mathcal{F}_n) =$ (так как случайная величина $z_{n+1}$ не зависит от $z_1,z_2,\ldots,z_n$) $= M_nE (a^{z_{n+1}}) =$ (по определению мартингала) $= M_n.$

Тогда

$E (a^{z_{n+1}})=1$

$E (a^{z_{n+1}})=\int\limits_0^1 a^t\,dt=1$

$\int\limits_0^1 e^{t\cdot\ln a}\,dt=\left. \dfrac{e^{t\cdot\ln a}}{\ln a}\right|_0^1=\dfrac{e^{\ln a}}{\ln a}-\dfrac1{\ln a}=\dfrac{e^{\ln a}-1}{\ln a}=\dfrac{a-1}{\ln a} = 1$ $\Rightarrow$

$\Rightarrow a-1=\ln a$

Это уравнение имеет единственное решение $a = 1.$

Получаем:

Процесс $M_n=a^{X_n}$ является мартингалом относительно фильтрации $\mathcal{F}_n$ только при $a = 1.$









