```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Винеровский процесс (Броуновское движение) {#wiener_process}

Конспект: Тимур Шакуров

дата: 2 декабря 2016

Переходим к изучению процессов в непрерывном времени: $t\in[0,\infty]$

Строго говоря, Винеровский процесс и Броуновское движение не одно и то же. [Броуновское движение](https://en.wikipedia.org/wiki/Brownian_motion) — это физический процесс, а [Винеровский процесс](https://en.wikipedia.org/wiki/Wiener_process) — его математическая модель.




## Определение Винеровского процесса 



$W_{t}$ — **Винеровский процесс** по отношению к фильтрации $\mathcal{F}$, если:

1. $W_{0}=0;$

2. $P\, (\text{траектория }  W_{t} \text{ непрерывна})=1;$

3. $\forall\; t \text{ величина } W_{t} \text{ измерима относительно } \sigma\text{-алгебры } \mathcal{F}_{t};$

4. $\text{Если } 0 \, \leq s \leq \, t \text{, то приращение } (W_{t}-W_{s}) \text{ не зависит от } \mathcal{F}_{s};$

5. $\text{Если } 0\, \leq s \leq \, t \text{, то } (W_{t}-W_{s}) \sim N(0;\, t-s).$

Можно показать, что эти свойства непротиворечивы. [Проверять это я конечно не буду.](https://www.youtube.com/watch?v=j978pwMZjmE)

Далее под $W_t$, если не указано иное, будем понимать Винеровский процесс.



## Упражнение №1

*Пусть $W_{t}$ — Винеровский процесс. Найти:*



а). $E(W_{t}), Var(W_{t})$;

5 свойство гласит, что $(W_{t}-W_{s}) \sim N(0;\, t-s)$.

Пусть $s=0$, тогда $W_s=W_0=0 \textit{ (согласно первому свойству) }\Rightarrow \; W_t\sim N(0; \; t) \Rightarrow  \; E(W_t)=0, Var(W_t)=t$

\                                                  

б). $Cov(W_{t}; W_{s})$;

$Cov(W_t; \, W_s)=Cov(W_s+W_t-W_s; \; W_S)=Cov(W_s; W_s)+Cov(W_t-W_s; \; W_s)=Var(W_s)+0=s$

(Согласно свойству 4, если  $0 \, \leq s \leq \, t$, то приращение $(W_{t}-W_{s})$ не зависит от $\mathcal{F}_{s}$,  а значит не зависит и от $W_s, \; \Rightarrow Cov(W_t-W_s; \, W_S)=0$).

\

в). $E(W_{t} \times W_{s})$;

$Cov(W_t, \, W_s)=E(W_t \times W_s) - E(W_t) \times E(W_s)$

$E(W_t \times W_s) = Cov(W_t, \,  W_s) + E(W_t) \times E(W_s)= s+0 \times 0=s$

\

г). $P\,(W_{7}-9W_{15}>0)$;

$W_7 \sim N(0; \, 7), 9W_{15} \sim N(0; \, 81 \times 15)$

Тогда случайная величина $(W_7-9W_{15})$ распределена нормально с мат. ожиданием $E(W_7-9W_{15})=E(W_7)-9E(W_{15})=0$.

Соответственно, вероятность того, что нормально распределенная случайная величина с нулевым мат. ожиданием больше нуля  $=\;{}^1/_2$ 

Во имя стохастического анализа, посчитаем еще и дисперсию:

$Var(W_7-9W_{15})=Var(W_7)+81Var(W_{15})+2Cov(W_7; -9W_{15})=7+81\times 15 -2\times 9Cov(W_7, W_{15})=1222-18\times 7=1096$

$(W_7-9W_{15})\sim N(0; 1096)$

\

д). $P\, (|W_{100}|>20)$.


$P\, (|W_{100}|>20)=P\, (|\frac{W_{100}}{10}|>2)\approx 5\%$ (2 $\approx$ 1.96 - ты узнаешь эти цифры из тысячи) 

$W_{100}\sim N(0; 100)$

$\frac{W_{100}-0}{\sqrt{100}}=\frac{W_{100}}{10} \sim N(0,1)$  

\

**Домашнее задание:**

$E(W_t^3), \; E(W_s-W_t^2), \; Cov(W_7; \; 2W_5+3W_8), \; P\,(W_7-W_5>5(W_6-W_4))$.

## Определение мартингала в непрерывном времени

У нас было определение мартингала в дискретном времени. Дадим определение мартингала в непрерывном времени.

Процесс $X_t$ — **мартингал** по отношению к фильтрации $F_t$, если:

1. $E(X_t) \; - существует;$

2. $\forall \; t \; величина \; X_t \; является \; \mathcal{F_t} - имзеримой;$

3. $\forall \; \Delta >0, \; \forall \; t: \; E(X_{t+\Delta}|\mathcal{F}_t)=X_t, \; \text{(т.е. наилучший прогноз будущего значения - текущее).}$

## Упражнение №2

*Проверить, являются ли мартингалами:*



а). $W_t$

$E(W_t)$ — существует, первое условие выполняется.

$\forall t \; W_t - \mathcal{F}_t $ - измерима, второе условие выполняется.

$E(W_{t+\Delta} |\mathcal{F}_t )=E(W_t+W_{t+\Delta}-W_t|\mathcal{F_t})=E(W_t|\mathcal{F}_t )+E(W_{t+\Delta}-W_t|\mathcal{F_t})=W_t+E(W_{t+\Delta}-W_t)=W_t$

(Согласно 4 и 5 свойствам Винеровских процессов: $E(W_{t+\Delta}-W_t|\mathcal{F_t})=E(W_{t+\Delta}-W_t)$ и  $E(W_{t+\Delta}-W_t)=0$)

$E(W_{t+\Delta}|\mathcal{F}_t )=W_t\Rightarrow W_t$ - мартингал

\

б). $Y_t=W_t^2$

$E(W_{t+\Delta}^2 |\mathcal{F}_t )=E((W_t+ (W_{t+\Delta}-W_t))^2|\mathcal{F_t})=E(W_t^2 +2W_t\times(W_{t+\Delta}-W_t)+ (W_{t+\Delta}-W_t)^2|\mathcal{F}_t )= E(W_t^2|\mathcal{F_t}) +2E(W_t\times(W_{t+\Delta}-W_t) |\mathcal{F_t}) + E((W_{t+\Delta}-W_t)^2|\mathcal{F_t})=W_t^2 +2W_t\times E(W_{t+\Delta}-W_t|\mathcal{F_t}) + E((W_{t+\Delta}-W_t)^2)=W_t^2 + E((W_{t+\Delta}-W_t)^2)$

$E((W_{t+\Delta}-W_t)^2)=Var(W_{t+\Delta}-W_t)+(E(W_{t+\Delta}-W_t))^2$

$(W_t-W_s)\sim N(0,t-s) \Rightarrow (W_{t+\Delta}-W_t) \sim N(0, \Delta)$

$E(W_{t+\Delta}-W_t)=0, Var(W_{t+\Delta}-W_t)=\Delta$

$E((W_{t+\Delta}-W_t)^2)=\Delta$

$E(W_{t+\Delta}^2 |\mathcal{F}_t )=W_t^2 + E((W_{t+\Delta}-W_t)^2)= W_t^2+\Delta \neq W_t^2 \Rightarrow W_t^2$ — не мартингал

\

**Домашнее задание:**

в). $Z=W_t^2-t \;$   г). $R_t=W_t^3 \;$    д). $N_t=6W_t+5$


