# Пример использования R Markdown {#06R_Markdown_example}

Конспект: Винни-Пух

Дата: 16 сентября 2016 г

## Подзаголовки так

Обычный текст печатается без решеток.

Формулы задаются в долларах, вот так: $a^2+b^2=c^2$,
                                      $S=\sqrt{p(p-a)(p-b)(p-c)}$.
Если хочется вывести формулу посредине, то синтаксис такой: 

\[
card\sigma(R,M)=2^{101\cdot51}
\]
                                      
События для сигма-алгебры тоже задаются в долларах. Cap и cup это пересечение и объединение соответственно: $A \cap ((B \Delta C) \cup D)$

Косинус сорока двух самому можно не считать. R знает его лучше вас. Просто сообщите ему эту команду в апострофах (З.Ы. буква ё на клавиатуре) и в конце властно поставьте точку : `r cos(42)`.

Для построения графика ступайте в Code -> Incert Chunk. Откроется такая штука ниже. Загрузите пакет в ggplot2 в R (если вы еще не позаботились о загрузке этого пакета с репозитория, то Tools->Install Packages и вводите названия пакетов,которые вам нужны). Здесь строим график, используя данные о спортивных машинах(cars), которые содержались в пакете ggplot2. По иксу откладываем скорость и подписываем эту ось, по игреку расстояние, и тоже подписываем:
```{r}
library("ggplot2")
qplot(data = cars, x = speed, y = dist) +
  xlab("Начальная скорость, миль/час") + ylab("Длина тормозного пути, футов")
```

Также можно указывать ссылки, например, на [почту](https://mail.ru/)

Можно загрузить картинку из Интернета, например [портрет самого Гаусса](http://dic.academic.ru/pictures/wiki/files/67/Carl_Friedrich_Gauss.jpg)

Или можно указать ссылку на учебник, например, на [Его величество LaTex](http://www.ccas.ru/voron/download/voron05latex.pdf)


Важные-важные уточнения: 

1. Cтроку language: ru-RU надо дописывать самому

1. Сохранять файл надо в UTF-8 

1. Русские буквы и пробелы в названии - страшный кошмар для R Markdown

1. Лучше выбирать формат Rmd для сохранения файла. Он универсален.

1. Необходимые пакеты для загрузки ищутся в Интернете по запросу со словами CRAN и RStudio

1. Для поиска необходимого символа для написания кода [рисуйте его в окошке слева, а справа будет список команд](http://detexify.kirelabs.org/classify.html)

1. Хороший [сайт с обозначениями символов в LaTex](http://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/)




