---
title: "Black-Scholes Model and Girsanov Theorem"
author: "Ksenia Kinyakina"
date: '16 декабря 2016 г '
output:
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true #можно поставить true, тогда будет красиво прокручиваться
    toc_depth: 3
    number_sections: true 
    theme: "readable"
    #highlight: "espresso"
    smart: true
  pdf_document:
    keep_tex: yes
lang: ru-RU
---

# Разбор задач из домашнего задания и новая модель в качестве финального аккорда

В данной лекции заявлены, как видно из названия, три основных issues, а именно задачи о славном дуэте леммы Ито и винеровского процесса, модель Блэка-Шоулза, а также теорема Гирсанова, на дессерт. В предверии зачёта рассмотрение этих понятий и решение нижеописанных задач будет как нельзя кстати. Поехали.

## Задачка номер раз

### Условия:

Посчитать $Var(\int_0^u W_a dW_a).$

### Решение:

Существует два пути решения: можно либо честно интегрировать, либо быстренько найти решение по свойствам. Разберём оба.

$Var(\int_0^u W_a dW_a) = Var(\frac{W_u^2 - u}{2}) = \frac{1}{4}Var(W_u^2 - u) = \frac{1}{4}Var(W_u^2) = \frac{1}{4}E(W_u^4) - \frac{1}{4}(E(W_u^4))^2$
Далее вспомним, что $W_u$ \~ $N(0; u),$ воспользовавшись "масштабированием", получим некоторую величину $Z = \frac{W_u - 0}{\sqrt{u}},$ получим, что $W_u = \sqrt{u}Z,$ где $Z \sim N(0; 1).$
Теперь $\frac{1}{4}E(W_u^4)$ можно переписать через $Z:$ $$\frac{1}{4}E(W_u^4) = E(u^2Z^4) = u^2E(Z^4) = u^2 \int_{-\infty}^{\infty} Z^4 f(Z) dZ,$$ где $f(Z) = \frac{1}{\sqrt{2\pi}} \exp^{\frac{-Z^2}{2}}.$

И тогда:
$$u^2 \int_{-\infty}^{\infty} Z^4 \frac{1}{\sqrt{2\pi}} \exp^{\frac{-Z^2}{2}} dZ = \frac{u^2}{\sqrt{2\pi}}\int_{-\infty}^{\infty} Z^4 \exp^{\frac{-Z^2}{2}} dZ.$$
Далее интегрируем по частям, где $u = Z^3, u' = 3Z^2, v = -\exp^{\frac{-Z^2}{2}}$:
$$\frac{u^2}{\sqrt{2\pi}}\int_{-\infty}^{\infty} Z^4 \exp^{\frac{-Z^2}{2}} dZ = \frac{u^2}{\sqrt{2\pi}}(-Z^3\exp^{\frac{-Z^2}{2}}|_{-\infty}^{\infty} - \int_{-\infty}^{\infty}\exp^{\frac{-Z^2}{2}} dZ) =$$
$$= \frac{u^2}{\sqrt{2\pi}}(-Z^3\exp^{\frac{-Z^2}{2}} + 3\int_{-\infty}^{\infty}Z^2\exp^{\frac{-Z^2}{2}} dZ) = u^2(3\int_{-\infty}^{\infty}\frac{1}{\sqrt{2\pi}}Z^2\exp^{\frac{-Z^2}{2}} dZ) = 3u^2.$$
Причём $3\int_{-\infty}^{\infty}Z^2\exp^{\frac{-Z^2}{2}} dZ = 3E(Z^2) = 3.$

Подставляем и получаем, что $$Var(\int_0^u W_a dW_a) = \frac{1}{4}3u^2 - u^2 = \frac{1}{2}u^2.$$

Итак, первое представленное (весьма громоздкое) решение можно считать разобранным, переходим ко второму пути решения. 

Оно следует из свойств Броуновского движения, рассмотренных на предыдущей лекции.
Воспользуемся теми фактами, что: 

$E(W_u^2) = Var(W_u^4) = u$

$Var(W_u) = E(W_u^2) - (E(W_u) )^2$

$u = E(W_u^2) = Var(W_u) \sim N(0; u).$

И тогда:
$$\int_{0}^{t}E(W_u^2) du = \int_{0}^{t}u du = \frac{1}{2}u^2|_0^t = \frac{1}{2}t^2.$$

Не стоит относиться с недоверием к тому, что в первом случае получено решение для $u$, а во втором для $t$, это лишь вопрос обозначения! :)

## Задачка номер два

### Условия:

Посчитать $Cov(W_t, \int_0^t W_u dW_u).$

### Решение:

$$Cov(W_t, \frac{W_t^2 - t}{2}) = E(W_t(\frac{W_t^2 - t}{2}) - E(W_t)E(\frac{W_t^2 - t}{2})) = E(W_t(\frac{W_t^2 - t}{2})) = E(\frac{W_t^3 - tW_t}{2}) = \frac{1}{2}(E(W_t^3) - E(tW_t)) = 0,$$ так как $E(W_t^3) = 0.$

Действительно, $E(\int_0^tW_u^{2016} dW_u) = E(I_t) = 0,$ так как $\int_0^tW_u^{2016} dW_u$ — мартингал, с математическим ожиданием равным нулю. Для другой степени при $W_u$ это тоже будет верно.

%## Задачка номер два с половиной

%Как будет выглядеть распределение для $y = Z^3$ относительно $y = Z?$

%```{r}
%x <- seq(-10, 10, length.out = 100000)
%Z_1 <- dnorm(x, mean = 0, sd = 1)
%Z_2 <- Z_1^3
%plot(x, Z_1, type = "l")
%lines(x, Z_2, type = "l", col = "green")
%```


## Краткая запись одной хорошей леммы

Лемма Ито в краткой записи получается, если как бы "разложить" функцию $f$ в ряд Тейлора до второго порядка и заменить: $dtdt \rightarrow 0, dW_tdt \rightarrow 0, dW_tdW_t \rightarrow dt.$

### Упражнение:
$dX_t = 5W_t^2dW_t + 6W_tdt; Y_t = X_t^2t^3.$

Записать $dY_t$ в краткой и полной форме.

Разложим в ряд Тейлора.

$$dY_t = f_{X_t}'d{X_t} + f_t'dt + \frac{1}{2}(f_{X_tX_t}''d{X_tdX_t} + f_{tt}''dtdt + 2f_{X_tt}''dX_tdt)$$ 

Подставляем $dX_t = 5W_t^2dW_t + 6W_tdt$ и получаем:

$$... = 2X_tt^3(5W_t^2dW_t + 6W_tdt) + 3t^2X_t^2dt + \frac{1}{2}(2t^3(5W_t^2dW_t + 6W_tdt)^2 + 12X_tt^2(5W_t^2dW_t + 6W_tdt)dt + 6X_t^2tdtdt).$$

Обнуляем те слагаемые, где встречаются $dtdt$ или $dW_tdt.$

$$Y_t = 10X_tt^3W_t^2dW_t + 12X_tt^3W_tdt + 3X_t^2t^2dt + 25t^3W_t^4dt.$$

В полной же форме $Y_t$ будет выглядеть так:

$$Y_t = Y_0 + \int_0^t 10X_uu^3W_u^2 dW_u + \int_0^t 12X_uu^3W_u du + \int_0^t 3X_u^2u^2 du + \int_0^t 25u^3W_u^4 du.$$

## Всё ещё подготовка к восприятию теоремы Блэка - Шоулза

+ $\sum(Y_i - Y_{i-1})^2$ сходится в смысле $L^2$ к $t \Rightarrow dW_tdW_t \rightarrow t$
+ $\sum(Y_i - Y_{i-1})\Delta{t}$ сходится в смысле $L^2$ к $0 \Rightarrow dW_tdt \rightarrow 0$
+ $\sum(\Delta{t})^2$ сходится в смысле $L^2$ к $0 \Rightarrow dtdt \rightarrow 0$

### Условия упражнения:

Пусть $S_t$ — цена акции в момент времени t
$dS_t = \mu S_tdt + \sigma S_tdW_t$

Найти:

a). $S_t$ — в полной форме записи

b). $d\log S_t$ — найти

c). Выразить в явном виде $S_t$

### Решение упражнения:

a).
$S_t = S_0 + \int_0^t\mu S_udu + \int_0^t\sigma S_udW_u$


b).
$d\log S_t = f_{S_t}'d{S_t} + \frac{1}{2}(f_{S_tS_t}''d{S_tdS_t} = \frac{1}{S_t}(\mu S_tdt + \sigma S_tdW_t) - \frac{1}{2S_t^2}(\mu S_tdt + \sigma S_tdW_t)^2 = \mu dt + \sigma dW_t - \frac{1}{2S_t^2}\mu S_tdt\mu S_tdt - \frac{2}{2S_t^2}\mu S_tdt\sigma S_tdW_t - \frac{1}{2S_t^2}\sigma S_tdW_t\sigma S_tdW_t = \mu dt + \sigma dW_t - \frac{1}{2}\sigma^2dt.$

Теперь запишем $\log S_t$ в полном виде:

$\log S_t = \log S_0 + \int_0^t \mu du + \int_0^t \sigma dW_u - \int_0^t \frac{1}{2} \sigma^2 du = \log S_0 + \mu t + \sigma W_t - \sigma W_0 - \frac{1}{2} \sigma^2 t.$


c).
Чтобы получить $S_t$, возьмём $\exp^{\log S_t}.$ Выходит, что $S_t = S_0 \exp^{\mu t + \sigma W_t - \frac{\sigma^2}{2} t}.$

Вопрос из аудитории: зачем она (теорема) нужна? Расчитывать цену акций, к примеру. Пусть $\Delta t = 1$ день, $\delta t = \frac{1}{365}.$ 

$\Delta \log S_t = \frac{1}{365} \mu  + \sigma(W_t - W_{t - \frac{1}{365}}) - \frac{1}{2} \frac{1}{365} \sigma^2$
$E(\Delta \log S_t) = \frac{1}{365} \mu - \frac{1}{2} \frac{1}{365} \sigma^2$
$Var(\Delta \log S_t) = \sigma^2 \frac{1}{365},$$ так как $W_t - W_s$ \~ $N(0; t-s).$ Оценив $\Delta \log S_t$ можно получить $\hat{\mu}$ и $\hat{\sigma}.$


### Нетривиальный факт:
Чтобы процесс сделать мартингалом, можно поменять вероятности.

Рассмотрим процеес $Y_1, Y_2.$ 

Процеес $Y_1, Y_2$ будет мартингалом, если $E(Y_2 | \mathcal{F}) = Y_1.$

||  $Y_2 = -2$  |  $Y_2 = 0$  |  $Y_2 = 2$  |
|:------:|:---:|:---:|:---:|
|  **$Y_1 = -1$** |  $a$  |  $b$  |  $0.8 - a - b$  |
|  **$Y_1 = 1$** |  $c$  |  $d$  |  $0.2 - c - d$  |

Надо подобрать значения $a, b, c, d$ так, чтобы ${Y_t}$ стал мартингалом, для этого следует "растащить" вероятность таким образом, чтобы $E(Y_2 | Y_1 = -1) = -1,$ например. 

|$Y_1$|$-1$|$1$|
|:------:|:---:|:---:|
|**$p$**|$0.8$|$0.2$|

В реальности мы сами вероятности менять, увы, не можем, но в теореме Блэка-Шоулза это возможно. Полезная вкусная фишка :)

## Теорема Гирсанова

Если $W_t$ — мартингал и броуновское движение относительно вероятности $p$ и $\widetilde{W}_t = W_t + \alpha t,$ то существует вероятность $\widetilde{p}$, относительно которой $\widetilde{W}_t$ — мартингал и броуновское движение.

Где $p$ - старые вероятности, $\widetilde{p}$ - новые вероятности, $W_t$ - мартингал и броуновское движение относительно $p$, $\widetilde{W}_t$ - не мартингал и не броуновское движение относительно $p$, но мартингал и броуновское движение относительно $\widetilde{p}$, при этом $W_t$ уже не будет мартингалом и броуновским движением относительно $\widetilde{p}$.


### Упражненьице ???

Пусть есть "хитрый" актив. В $t$ его цена произвольно связана с прибылью. В момент времени $T$ владелец актива получает $S^2_T$ рублей. $Х_t$ — цена актива в момент $t$. Скажем, что есть некая безрисковая процентная ставка $r$. 