---
title: "Стохастический анализ"
output:
  html_document: default
  pdf_document: default
lang: ru-RU
---


## Материалы

* [Учебник](https://github.com/bdemeshev/sc_book/raw/master/sc_book.pdf) (черновик)
* Прототип [задачника](https://github.com/bdemeshev/sc401/raw/master/sc_pset/sc_problems_main.pdf)
* Теорема Дуба [об остановке мартингала](https://github.com/bdemeshev/sc401/raw/master/stop_theorem/stop_theorem_main.pdf)
* [Видео-запись](http://www.youtube.com/playlist?list=PL1poMUvVlAqeZOvhE75ViZPKnCTmWLRxf) лекций Димы Борзых для 2 курса бакалавриата экономики



## ICEF master course

* [Hometask-2018](https://github.com/bdemeshev/sc401/raw/master/2018_icef/hometask/hometask_2018.pdf)
* Exams [collection](https://github.com/bdemeshev/sc401/raw/master/matek2_collect/matek2_collection.pdf)
* Some video [lectures-2013](https://vimeo.com/album/2609503) 
* Student lecture notes-2016:
    - lecture 1: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_01.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_01.tex)
    - lecture 2: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_02.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_02.tex)
    - lecture 3: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_03.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_03.tex) 
    - lecture 4: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_04.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_04.tex) 
    - lecture 5: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_05.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_05.tex) 
    - lecture 6: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_06.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_06.tex) 
    - lecture 7: [pdf](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_07.pdf), [tex](https://github.com/bdemeshev/sc401/raw/master/2016_icef/stud_notes/sc_icef_lect_07.tex)

## Курс в РАНХиГС

* [Домашнее задание - 2015](https://github.com/bdemeshev/sc401/raw/master/ranepa_st/2015/dz_ranh/sc_dz_ranh.pdf). 
* [Конспект курса - 2016](http://bdemeshev.github.io/sc401/notes_ranepa_2016/). Для конспектирующих [типичные .Rmd-файлы](https://github.com/bdemeshev/sc401/tree/master/ranepa_st/2016/lecture_notes_book) 
* Контрольная [работа-2016](https://github.com/bdemeshev/sc401/raw/master/ranepa_st/2016/kr_01/kr_01_sc_ranepa.pdf) :) 


## Курс в банковском институте

* Зачёт [2014](https://github.com/bdemeshev/sc401/raw/master/binst_2014/zachet_14/zach_14.pdf)
* Заметки-2014 от [Ассель](https://github.com/bdemeshev/sc401/raw/master/binst_2014/binst_sc_assel_notes.pdf)
и [Полины](https://github.com/bdemeshev/sc401/raw/master/binst_2014/binst_sc_polina_notes.pdf)
* Скрипты 2014: [условное ожидание](https://github.com/bdemeshev/sc401/raw/master/binst_2014/binst_2014_01_25_cond_exp.R), [винеровский процесс](https://github.com/bdemeshev/sc401/raw/master/binst_2014/binst_2014_3_wiener_ito.R), [оценка опциона](https://github.com/bdemeshev/sc401/raw/master/binst_2014/binst_2014_option_price.R)
* Зачёт [2015](https://github.com/bdemeshev/sc401/raw/master/binst_2015/zachet_15.pdf)
* 2016: Оценивание опциона с [помощью симуляций в R](https://github.com/bdemeshev/sc401/raw/master/binst_2016/sem_01.R)
* Зачёт [2016](https://github.com/bdemeshev/sc401/raw/master/binst_2016/zach_16/zach_16.pdf)
* Зачёт [2017](https://github.com/bdemeshev/sc401/raw/master/binst_2017/zach_2017/sc_binst_2017.pdf). Срок сдачи домашнего задания: 8 июня. Разумнее всего принести его в печатном виде в комнату 2112. Если там никого нет, то можно просунуть его под дверь, я заберу как появлюсь. 



## Ссылки

* Gary Schurman, [Applied Business Economics Classroom](http://www.appliedbusinesseconomics.com/webClassroom.htm) Несколько доказательств формулы Блэка-Шоулса и много других вкусностей
* Robert Ash, Probability and Measure Theory
* René L. Schilling, [Measures, Integrals and Martingales](http://blog.sciencenet.cn/home.php?mod=attachment&filename=Measures%2C%20Integrals%20and%20Martingales.pdf&id=45541)
* Ivan Wilde, [Stochastic calculus](https://github.com/bdemeshev/sc401/raw/master/materials/ivan_wilde_stochastic_analysis_notes.pdf)
* Ivan Wilde, [Measure and probability](https://github.com/bdemeshev/sc401/raw/master/materials/ivan_wilde_measure_integration_probability.pdf)
* Silke Göbel, [The mathematician Wolfgang Doeblin](http://www.zentralblatt-math.org/year-of-mathematics/yom-11.pdf), краткая история о первооткрывателе формулы Ито
* Joe Chang, [Stochastic processes](http://www.stat.yale.edu/~pollard/Courses/251.spring09/Handouts/Chang-notes.pdf)
* David Pollard, [Stochastic processes](http://www.stat.yale.edu/~pollard/Courses/251.spring09/) course: шикарный курс с кучей доп. материалов и идеями проектов
* Thomas Mikosch, [Elementary stochastic calculus with finance in view](https://goo.gl/Oz827mf)
* Ovidiu Calin, [An Introduction to Stochastic Calculus with Applications
to Finance](https://people.emich.edu/ocalin/Teaching_files/D18N.pdf). Добротный курс — отличный ориентир!
* Gregory Lawler, [Stochastic Calculus: An Introduction with
Applications](http://www.math.uchicago.edu/~lawler/finbook2.pdf). Есть упражнения и процессы со скачками.
* Martin Haug, [Introduction, 18 pages](http://www.columbia.edu/~mh2078/stochastic_calculus.pdf)


## Кто такой Марков и почему он размахивает цепями? 

* James Norris, [Markov Chains](http://www.statslab.cam.ac.uk/~rrw1/markov/M.pdf) --- короткий вменяемый текст по марковским цепям. Есть красивейшие штучки, но и занудства в начале хватает :)
* Шесть [видеолекций на lektorium.tv](https://www.lektorium.tv/course/22882) и [заметки к ним](http://www.win.tue.nl/~jkomjath/SPBlecturenotes.pdf)
* Yuval Peres, [Markov chains and mixing times](http://www.cs.cmu.edu/~15859n/RelatedWork/MarkovChains-MixingTimes.pdf)
* [ams](http://www.ams.org/bookstore/pspdf/mbk-58-prev.pdf)
* Jeff Gill, [Primer on MCMC](http://www4.stat.ncsu.edu/~sghosh/TEACHING/st790/lectures/GillMCMC.pdf)



## Книжки:

* Chang, Stochastic optimization in continuous time
* Michael Steele, Stochastic calculus and financial applications
* Steven Shreve, Stochastic Calculus for Finance I, II

-------
Созданные мной для данного курса материалы распространяются по лицензии [Creative Commons Attribution-NonCommercial-ShareAlike](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.ru)
